### ISSUE TITLE
NameError: name 'super' is not defined

### ISSUE THREAD

**Issue by gmoneyomics** [giesselmann/STRique#2]
Hi, 

I am trying to run the test script:

 cat data/c9orf72.sam | python3 scripts/STRique.py ./data ./models/template_median68pA6mer.model ./configs/repeat_config.tsv --config ./configs/STRique.json

/usr/lib/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
ID	target	strand	count	score_prefix	score_suffix	log_p	offset	ticks
Traceback (most recent call last):
  File "scripts/STRique.py", line 765, in <module>
    ow.write_line(**counts)                
TypeError: write_line() argument after ** must be a mapping, not NoneType
Traceback (most recent call last):
  File "scripts/STRique.py", line 341, in free_bake_buffers
NameError: name 'super' is not defined
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel.__dealloc__'
Traceback (most recent call last):
  File "scripts/STRique.py", line 341, in free_bake_buffers
NameError: name 'super' is not defined
Segmentation fault (core dumped)

**Comment by giesselmann** [comment]
Hi,
that's indeed a bug, I wasn't filtering for sam header lines in the input. 
Fixed in version 0.1.1

**Comment by LynnLy** [comment]
Thanks for the neat pipeline. 

I'm also still getting `NameError: name 'super' is not defined`. 

Commenting out `def free_bake_buffers(self):` and `super().free_bake_buffers()` in lines 340-341 of STRique.py makes the tests work. I haven't figured out why, as all the other usages of `super()` seem to work fine. I did not see free_bake_buffers called ever again except for in these lines, so maybe it is unnecessary.

**Comment by giesselmann** [comment]
Hey,

can you paste the full stack trace of the error in your case. Last time the 'super not defined' was not the error but only the point where the worker process crashed. Please also make sure to re-install STRique in a clean (virtual) environment. Especially the networkx dependency of pomegranate is a bit unstable. 

Pay

**Comment by LynnLy** [comment]
Oh, I see! My installation is in its own conda environment. I get: 

```cat data/c9orf72.sam | python3 scripts/STRique.py ./data ./models/template_median68pA6mer.model ./configs/repeat_config.tsv --config ./configs/STRique.json
ID      target  strand  count   score_prefix    score_suffix    log_p   offset  ticks
/home/lly/miniconda3/envs/strique/lib/python3.6/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
ce47b364-ed6e-4409-808a-1041c0b5aac2    c9orf72 -       735     6.3155927807600545      6.031860427335506       -119860.52066647023     1633    40758
Traceback (most recent call last):
  File "scripts/STRique.py", line 341, in free_bake_buffers
NameError: name 'super' is not defined
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel.__dealloc__'
Traceback (most recent call last):
  File "scripts/STRique.py", line 341, in free_bake_buffers
NameError: name 'super' is not defined
Traceback (most recent call last):
  File "scripts/STRique.py", line 341, in free_bake_buffers
NameError: name 'super' is not defined
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel.__dealloc__'
Traceback (most recent call last):
  File "scripts/STRique.py", line 341, in free_bake_buffers
NameError: name 'super' is not defined
*** Error in `python3': double free or corruption (!prev): 0x000055900a8f6460 ***
```

And the backtrace / memory map, slightly shortened:

```
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ff83cf3b7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ff83cf4437a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ff83cf4853c]
/home/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/hmm.cpython-36m-x86_64-linux-gnu.so(+0x2436e)[0x7ff8399c336e]
python3(+0x1a45fc)[0x5590089265fc]
python3(+0xf28d7)[0x5590088748d7]
python3(+0xf2767)[0x559008874767]
python3(PyDict_SetItem+0x3da)[0x5590088bbc4a]
python3(PyErr_PrintEx+0xd6)[0x559008994b06]
/home/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/hmm.cpython-36m-x86_64-linux-gnu.so(+0x17c91)[0x7ff8399b6c91]
/home/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/hmm.cpython-36m-x86_64-linux-gnu.so(+0x24678)[0x7ff8399c3678]
python3(+0x1a45fc)[0x5590089265fc]
...
python3(+0x1a45de)[0x5590089265de]
python3(PyDict_Clear+0x13b)[0x559008873c2b]
python3(+0xf1cfa)[0x559008873cfa]
python3(+0x14d1c1)[0x5590088cf1c1]
python3(_PyGC_CollectNoFail+0x2a)[0x55900896e32a]
python3(PyImport_Cleanup+0x278)[0x559008930e68]
python3(Py_FinalizeEx+0x61)[0x5590089947a1]
python3(Py_Exit+0x9)[0x559008994909]
python3(+0x2129f8)[0x5590089949f8]
python3(PyErr_PrintEx+0x32)[0x559008994a62]
python3(PyRun_SimpleFileExFlags+0x247)[0x55900899b317]
python3(Py_Main+0x659)[0x55900899edc9]
python3(main+0xee)[0x55900886644e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ff83cee4830]
python3(+0x1ccd7f)[0x55900894ed7f]
======= Memory map: ========
linux-gnu.so
7ff7e9b1f000-7ff7e9b22000 r--p 00000000 00:33 7700317                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/ExponentialDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b22000-7ff7e9b27000 r-xp 00003000 00:33 7700317                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/ExponentialDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b27000-7ff7e9b29000 r--p 00008000 00:33 7700317                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/ExponentialDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b29000-7ff7e9b2a000 r--p 00009000 00:33 7700317                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/ExponentialDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b2a000-7ff7e9b2b000 rw-p 0000a000 00:33 7700317                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/ExponentialDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b2b000-7ff7e9b2f000 r--p 00000000 00:33 7700323                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/LogNormalDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b2f000-7ff7e9b35000 r-xp 00004000 00:33 7700323                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/LogNormalDistribution.cpython-36m-x8                
...
7ff7e9b1d000-7ff7e9b1e000 r--p 0000a000 00:33 7700319                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/BetaDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b1e000-7ff7e9b1f000 rw-p 0000b000 00:33 7700319                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/BetaDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b1f000-7ff7e9b22000 r--p 00000000 00:33 7700317                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/ExponentialDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b22000-7ff7e9b27000 r-xp 00003000 00:33 7700317                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/ExponentialDistribution.cpython-36m-x86_64-linux-gnu.so
...
7ff7e9b86000-7ff7e9b87000 rw-p 0000c000 00:33 7700321                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/NormalDistribution.cpython-36m-x86_64-linux-gnu.so
7ff7e9b87000-7ff7e9b8a000 r--p 00000000 00:33 7700314                    /nfs/sfohome/lly/miniconda3/envs/strique/lib/python3.6/site-packages/pomegranate/distributions/BernoulliDistribution.cpython-36m-x86_64-linux-gnu.soAborted
```

**Comment by giesselmann** [comment]
Thank you!
This is indeed interesting as in between of all the errors the correct output line appears. I have to check why we explicitly called the free_bake_buffers(), I'm not convinced we can just skip it. 
I'll have to check a few things, coming back here with a fix soon.
Pay

**Comment by LynnLy** [comment]
I'd like to update that I have STRique working on a real dataset, and it does not produce any errors. For some reason, it only occurs on the test dataset. Thanks for looking into it!

**Comment by LynnLy** [comment]
I was able to reproduce this error on a real dataset. It happens whenever I set threads `--t` to 1 or something low. I usually set `--t` to 20 and it always works now. Cheers!

**Comment by giesselmann** [comment]
Hey @LynnLy 
thank you for further looking into the issue. Is it '--t to 1' exclusively or as you describe also with small --t? I'm asking because the code path for --t == 1 is different to --t > 1. 
I'll try to reproduce the behavior in the meantime.

**Comment by LynnLy** [comment]
@giesselmann You are right, it seems to only occur with --t == 1
